#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
for slave in `$SCRIPT_DIR/get-slaves`
do
  ssh $slave "ps aux | grep -v stop-nmon | grep -v general-test | grep '[n]mon' | awk '{print \$2}' | xargs kill -9"
done
